# https://github.com/opentensor/subtensor/blob/main/docker-compose.yml

services:
  mainnet-archive:
    image: ghcr.io/opentensor/subtensor:v1.1.8
    cpu_count: 4
    mem_limit: 40000000000
    memswap_limit: 80000000000
    ports:
      - "9944:9944"
      - "30333:30333"
      - "9933:9933"
    expose:
      - "9944"
      - "30333"
      - "9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    container_name: subtensor-mainnet-archive
    volumes:
      - /mnt/disks/subtensor-persistent-storage/finney:/tmp/blockchain
    command:
      - /bin/bash
      - -c
      - |
        node-subtensor \
          --base-path /tmp/blockchain \
          --chain raw_spec_finney.json \
          --rpc-external --rpc-cors all \
          --no-mdns \
          --in-peers 500 --out-peers 500 \
          --bootnodes /dns/bootnode.finney.chain.opentensor.ai/tcp/30333/ws/p2p/12D3KooWRwbMb85RWnT8DSXSYMWQtuDwh4LJzndoRrTDotTR5gDC \
          --pruning=archive
